### ISSUE TITLE
Error bar to the top only?

### ISSUE THREAD

**Issue by makostadima** [tercen/barplot_operator#3]
Is there any way to control the error bar, so that it only appears on top of the bars? Like in this figure:

![image](https://user-images.githubusercontent.com/1746464/180158678-ffd82295-45fa-4675-b767-f8ce0ac32164.png)

And is this good practice or should be avoided as misleading?

**Comment by agouy** [comment]
There would be a way of implementing it I guess but I would not recommend doing it, unless there is a very good reason to do so
