### ISSUE TITLE
Issue with barplot output

### ISSUE THREAD

**Issue by agouy** [tercen/barplot_operator#4]
Check also this step: https://tercen.com/test-team/w/3d0482ed7ae6c2f2d24e5678cd5af239/ds/bbca4146-337c-468f-be93-280d29849c1f/crosstab

What I get in the computed barplot isn't what I expected, as not every group contain two measurements in the resulting barplot and the y axis range is much smaller than it should.

In this example I have only one measurement per color group within each x-axis tick.

_Originally posted by @makostadima in https://github.com/tercen/barplot_operator/issues/1#issuecomment-1181872475_

**Comment by agouy** [comment]
Happens because dodge_width parameter is set to 0, hence disabling the dodge feature (default is 1.1 in the operator)

**Comment by makostadima** [comment]
So there is no way to display stacked bars?

**Comment by agouy** [comment]
There would be a way but so far only "grouped" bar charts are supported (position = "dodge"). We would have to add another parameter to select between "grouped", "stacked" or "percent stacked", see [here](https://r-graph-gallery.com/48-grouped-barplot-with-ggplot2). I'll create a new issue for that.
