### ISSUE TITLE
GitHub version problem on GUI

### ISSUE THREAD

**Issue by martin1english** [tercen/barplot_operator#8]
![image](https://user-images.githubusercontent.com/64135638/202724841-1fb42e0e-ec77-4010-b383-b39e8f10e5f9.png)

The barplot has a weird string instead of a version number.
It causes problem with the GUI if this operator is selected.

**Comment by agouy** [comment]
This is a development version, visible only if such a version has been installed in the team. There might be a few that have not been uninstalled, I'll review them and delete the ones that are part of the tercen team.
Such versions will never be part of the app library, they have to be installed by a developer in a team (and will be part of the "installed operators" in this team only).

**Comment by agouy** [comment]
@martin1english , in which team were you working?

**Comment by martin1english** [comment]
Hi Alex
I was working on the Dev server so maybe this is an invalid issue.
